'use strict';
// Fragenbestand.
//
// STATUS: alle im Status "entwurf" - eigenständig verfasst, ohne Rückgriff auf
// fremde Skripten oder Prüfungsangaben (Kapitel 13). Vor Verkauf ersetzen bzw.
// durch den Kursgeber freigeben. difficulty: -2 leicht bis +2 schwer.
//
// type: 'mc'   -> options + answer = Index der richtigen Option
//       'tf'   -> answer = 0 (Richtig) oder 1 (Falsch)
//       'norm' -> answer = Array akzeptierter Eingaben (normalisierter Vergleich)

const TF = ['Richtig', 'Falsch'];

const mc = (id, topic, stem, options, answer, explanation, difficulty = 0, diag = false) =>
  ({ id, topic_id: topic, type: 'mc', stem, options, answer, explanation, difficulty, in_diagnostic: diag ? 1 : 0, status: 'entwurf' });
const tf = (id, topic, stem, answer, explanation, difficulty = 0, diag = false) =>
  ({ id, topic_id: topic, type: 'tf', stem, options: TF, answer, explanation, difficulty, in_diagnostic: diag ? 1 : 0, status: 'entwurf' });
const norm = (id, topic, stem, answers, explanation, difficulty = 0.5, diag = false) =>
  ({ id, topic_id: topic, type: 'norm', stem, options: [], answer: answers, explanation, difficulty, in_diagnostic: diag ? 1 : 0, status: 'entwurf' });

module.exports = [
  // ---------------- Methodenlehre ----------------
  mc('q-m-rq-1', 'm-rechtsquellen',
    'Eine Verordnung widerspricht dem Gesetz, auf dessen Grundlage sie erlassen wurde. Was gilt?',
    ['Sie ist automatisch nichtig und von jedermann zu ignorieren',
     'Sie ist gesetzwidrig, bleibt aber anwendbar, bis sie aufgehoben wird',
     'Sie geht dem Gesetz als speziellere Norm vor',
     'Sie wird durch den Widerspruch zum Gesetz erhoben'],
    1, 'Der Stufenbau ordnet den Rang, hebt die rangniedrigere Norm aber nicht von selbst auf. Die Aufhebung ist Sache des Verfassungsgerichtshofs.', 0.4, true),
  tf('q-m-rq-2', 'm-rechtsquellen',
    'Unionsrecht hebt entgegenstehendes österreichisches Recht auf.',
    1, 'Die Aussage trifft nicht zu. Unionsrecht hat Anwendungsvorrang: die nationale Norm bleibt im Rechtsbestand, wird im konkreten Fall aber nicht angewendet.', 0.6, true),
  mc('q-m-rq-3', 'm-rechtsquellen',
    'Welche der folgenden Normen ist eine individuelle Norm?',
    ['Bundesgesetz', 'Verordnung', 'Bescheid', 'Verfassungsbestimmung'],
    2, 'Bescheid und Urteil richten sich an bestimmte Personen im Einzelfall und stehen daher auf der untersten Stufe.', -0.6, true),

  mc('q-m-ausl-1', 'm-auslegung',
    'Welche Auslegungsmethode markiert die äußere Grenze jeder Auslegung?',
    ['die systematische', 'die historische', 'die teleologische', 'die Wortinterpretation'],
    3, 'Was der mögliche Wortsinn nicht mehr trägt, ist nicht mehr Auslegung, sondern Rechtsfortbildung.', -0.2, true),
  mc('q-m-ausl-2', 'm-auslegung',
    'Ein Gericht stützt sich auf die Erläuterungen zur Regierungsvorlage. Welche Methode wendet es an?',
    ['systematische Auslegung', 'historische Auslegung', 'teleologische Auslegung', 'Wortinterpretation'],
    1, 'Materialien wie Erläuterungen dokumentieren den Willen des historischen Gesetzgebers.', 0.1, true),
  tf('q-m-ausl-3', 'm-auslegung',
    'Zwischen den vier Auslegungsmethoden besteht eine feste Rangordnung, die stets einzuhalten ist.',
    1, 'Die Aussage trifft nicht zu. Der Wortlaut ist Ausgangspunkt und Grenze, eine starre Rangfolge der übrigen Methoden besteht nicht - sie werden abgewogen.', 0.8),

  mc('q-m-lue-1', 'm-lueckenschluss',
    'Voraussetzung jeder Analogie ist',
    ['eine ausdrückliche gesetzliche Ermächtigung',
     'eine planwidrige Unvollständigkeit des Gesetzes',
     'die Zustimmung der Parteien',
     'ein Urteil des Obersten Gerichtshofs'],
    1, 'Ohne Planwidrigkeit liegt beredtes Schweigen vor - dann ist der Umkehrschluss zu ziehen, nicht die Analogie.', 0.3, true),
  tf('q-m-lue-2', 'm-lueckenschluss',
    'Im Strafrecht ist die Analogie zulasten des Täters zulässig, wenn der Zweck der Norm sie trägt.',
    1, 'Die Aussage trifft nicht zu. Aus dem Grundsatz keine Strafe ohne Gesetz folgt das Verbot der Analogie zulasten des Täters.', 0.2, true),
  mc('q-m-lue-3', 'm-lueckenschluss',
    'Analogieschluss und Umkehrschluss unterscheiden sich vor allem darin, dass',
    ['der Umkehrschluss nur im öffentlichen Recht gilt',
     'sie an dieselbe Beobachtung anknüpfen, aber zum entgegengesetzten Ergebnis führen',
     'der Analogieschluss zwingend ist, der Umkehrschluss fakultativ',
     'nur der Analogieschluss eine Wertung erfordert'],
    1, 'Beide setzen an der Nichtregelung des Falles an. Welcher Schluss zutrifft, entscheidet der Normzweck.', 0.7),

  mc('q-m-sub-1', 'm-subsumtion',
    'Der Obersatz im Gutachten beantwortet welche Frage?',
    ['Wie lautet das Ergebnis?', 'Wer will was von wem woraus?',
     'Welche Meinungen werden vertreten?', 'Welche Norm ist die jüngste?'],
    1, 'Der Obersatz benennt Anspruchsteller, Begehren, Gegner und Anspruchsgrundlage.', -0.4, true),
  mc('q-m-sub-2', 'm-subsumtion',
    'In welchem Schritt des Gutachtens werden die meisten Punkte vergeben?',
    ['Obersatz', 'Definition', 'Subsumtion', 'Ergebnis'],
    2, 'Die Subsumtion ist der einzige Schritt, in dem tatsächlich argumentiert wird.', -0.1, true),
  tf('q-m-sub-3', 'm-subsumtion',
    'Der Urteilsstil beginnt mit dem Ergebnis, der Gutachtenstil endet damit.',
    0, 'Die Aussage trifft zu. Deshalb macht nur der Gutachtenstil den Gedankengang sichtbar - und nur der wird bewertet.', -0.3, true),
  mc('q-m-sub-4', 'm-subsumtion',
    'Ein Tatbestandsmerkmal ist im Sachverhalt eindeutig erfuellt und zwischen den Beteiligten unstreitig. Wie behandelt man es?',
    ['ausführlich im Gutachtenstil erörtern',
     'knapp feststellen und zum problematischen Merkmal weitergehen',
     'ganz weglassen', 'als Hilfsgutachten am Ende prüfen'],
    1, 'Zeit ist die knappste Ressource der Klausur. Unproblematisches wird festgestellt, nicht diskutiert.', 0.4),

  tf('q-m-gelt-1', 'm-geltung',
    'Ein später erlassenes einfaches Bundesgesetz verdrängt eine ältere Verfassungsbestimmung.',
    1, 'Die Aussage trifft nicht zu. Die Kollisionsregel lex posterior gilt nur unter ranggleichen Normen; der Rang geht der Zeit vor.', 0.5, true),
  mc('q-m-gelt-2', 'm-geltung',
    'Welche Regel besagt, dass die speziellere Norm der allgemeineren vorgeht?',
    ['lex posterior derogat legi priori', 'lex specialis derogat legi generali',
     'lex superior derogat legi inferiori', 'in dubio pro reo'],
    1, 'Die Spezialitätsregel setzt gleichen Rang voraus.', -0.2),

  // ---------------- Zivilrecht ----------------
  mc('q-z-pa-1', 'z-privatautonomie',
    'Was kennzeichnet das Privatrecht gegenüber dem öffentlichen Recht?',
    ['Es ist jünger', 'Die Beteiligten stehen einander gleichgeordnet gegenüber',
     'Es wird nur von Gerichten angewendet', 'Es ist stets dispositiv'],
    1, 'Maßgeblich ist die Gleichordnung. Im öffentlichen Recht besteht ein Über- und Unterordnungsverhältnis.', -0.5, true),
  mc('q-z-pa-2', 'z-privatautonomie',
    'Dispositives Recht bedeutet, dass die Regel',
    ['nur für Unternehmer gilt', 'nur gilt, wenn die Parteien nichts anderes vereinbaren',
     'jederzeit vom Gericht geändert werden kann', 'Verfassungsrang hat'],
    1, 'Dispositives Recht ist ein Ersatzprogramm für den Fall, dass die Parteien schweigen.', 0.0, true),
  tf('q-z-pa-3', 'z-privatautonomie',
    'Zwingendes Recht dient häufig dem Ausgleich einer strukturellen Verhandlungsunterlegenheit.',
    0, 'Die Aussage trifft zu. Konsumenten-, Miet- und Arbeitsrecht sind die typischen Felder.', 0.1),

  mc('q-z-rs-1', 'z-rechtssubjekte',
    'Ab wann ist eine natürliche Person rechtsfähig?',
    ['mit Vollendung des 14. Lebensjahres', 'mit der Geburt',
     'mit Vollendung des 18. Lebensjahres', 'mit der Eintragung im Zentralen Melderegister'],
    1, 'Die Rechtsfähigkeit beginnt mit der Geburt; das bereits gezeugte Kind wird unter Voraussetzungen berücksichtigt.', -0.8, true),
  mc('q-z-rs-2', 'z-rechtssubjekte',
    'Eine 15-jährige Schülerin schließt ohne Wissen der Eltern einen Handyvertrag mit hoher monatlicher Belastung. Welche Fähigkeit ist zu prüfen?',
    ['Rechtsfähigkeit', 'Geschäftsfähigkeit', 'Deliktsfähigkeit', 'Prozessfähigkeit'],
    1, 'Es geht darum, ob sie sich durch eigenes Handeln wirksam binden kann - das ist die Geschäftsfähigkeit.', 0.2, true),
  tf('q-z-rs-3', 'z-rechtssubjekte',
    'Geschäftsfähigkeit und Deliktsfähigkeit treten stets zum selben Zeitpunkt ein.',
    1, 'Die Aussage trifft nicht zu. Beide folgen eigenen Regeln; mündige Minderjährige sind deliktsfähig, aber nicht voll geschäftsfähig.', 0.6),

  mc('q-z-rg-1', 'z-rechtsgeschaeft',
    'Wie ist eine Willenserklärung auszulegen?',
    ['nach dem inneren Willen der Erklärenden',
     'so, wie ein redlicher Erklärungsempfänger sie verstehen durfte',
     'stets wörtlich', 'nach der Verkehrssitte am Wohnort der Erklärenden'],
    1, 'Der Vertrauensschutz des Empfängers geht vor - deshalb braucht es überhaupt ein Irrtumsrecht.', 0.3, true),
  tf('q-z-rg-2', 'z-rechtsgeschaeft',
    'Schweigen gilt im Privatrecht grundsätzlich als Zustimmung.',
    1, 'Die Aussage trifft nicht zu. Schweigen ist grundsätzlich keine Erklärung; Ausnahmen brauchen eine besondere Grundlage.', -0.2, true),
  mc('q-z-rg-3', 'z-rechtsgeschaeft',
    'Ein Motivirrtum ist bei entgeltlichen Geschäften',
    ['immer beachtlich', 'grundsätzlich unbeachtlich',
     'nur bei Grundstücken beachtlich', 'nur bei Verbrauchern beachtlich'],
    1, 'Das Motiv liegt außerhalb des Erklärungsinhalts; das Risiko trägt grundsätzlich die Irrende.', 0.9),

  mc('q-z-v-1', 'z-vertrag',
    'Die Warenpräsentation im Schaufenster ist rechtlich regelmäßig',
    ['ein bindendes Angebot', 'eine Einladung zum Anbieten',
     'eine Annahme', 'ein Vorvertrag'],
    1, 'Es fehlt der Bindungswille - sonst müsste die Händlerin an jede Person liefern, auch bei erschöpftem Vorrat.', 0.1, true),
  mc('q-z-v-2', 'z-vertrag',
    'B antwortet auf ein Angebot: "Einverstanden, aber der Liefertermin muss zwei Wochen früher sein." Rechtlich ist das',
    ['eine wirksame Annahme', 'ein neues Angebot',
     'ein Widerruf', 'eine unbeachtliche Nebenabrede'],
    1, 'Eine Annahme unter Änderungen gilt als Ablehnung verbunden mit einem neuen Angebot.', 0.3, true),
  tf('q-z-v-3', 'z-vertrag',
    'Bei digitalen Inhalten erlischt das Rücktrittsrecht auch ohne ausdrückliche Zustimmung zum vorzeitigen Beginn, sobald der Download startet.',
    1, 'Die Aussage trifft nicht zu. Es braucht die ausdrückliche Zustimmung UND die Bestätigung der Kenntnis vom Verlust des Rücktrittsrechts.', 0.7, true),

  mc('q-z-se-1', 'z-schadenersatz',
    'Welche Voraussetzung gehört NICHT zum Grundtatbestand des Schadenersatzes?',
    ['Schaden', 'Kausalität', 'Rechtswidrigkeit', 'Bereicherung des Schädiger'],
    3, 'Die Bereicherung gehört ins Bereicherungsrecht, nicht ins Schadenersatzrecht.', -0.3, true),
  mc('q-z-se-2', 'z-schadenersatz',
    'Wozu dient die Lehre vom Schutzzweck der Norm?',
    ['zur Erhöhung des Schadenersatzes', 'zur Begrenzung der zu weiten Äquivalenzkausalität',
     'zur Bestimmung der Verjährung', 'zur Beweislastumkehr'],
    1, 'Ersetzt wird nur der Schaden, dessen Eintritt die verletzte Norm verhindern wollte.', 0.8),
  tf('q-z-se-3', 'z-schadenersatz',
    'Der Sorgfaltsmaßstab im Zivilrecht ist grundsätzlich objektiv.',
    0, 'Die Aussage trifft zu. Maßgeblich ist die von einer durchschnittlich sorgfältigen Person zu erwartende Sorgfalt.', 0.4),

  // ---------------- Öffentliches Recht ----------------
  mc('q-o-bg-1', 'o-baugesetze',
    'Welches Prinzip zählt NICHT zu den Baugesetzen der Bundesverfassung?',
    ['demokratisches Prinzip', 'bundesstaatliches Prinzip',
     'monarchisches Prinzip', 'rechtsstaatliches Prinzip'],
    2, 'Das republikanische Prinzip ist gerade das Gegenteil - Österreich ist eine Republik.', -0.7, true),
  tf('q-o-bg-2', 'o-baugesetze',
    'Eine Gesamtänderung der Bundesverfassung erfordert zwingend eine Volksabstimmung.',
    0, 'Die Aussage trifft zu. Das ist die zusätzliche Hürde, die die Baugesetze schützt.', 0.2, true),
  mc('q-o-bg-3', 'o-baugesetze',
    'Warum werden die tragenden Prinzipien "Baugesetze" genannt?',
    ['weil sie in einem eigenen Baugesetz stehen',
     'weil ihre Beseitigung die Verfassung als Ganzes verändern würde',
     'weil sie das Baurecht regeln', 'weil sie 1920 zuletzt geändert wurden'],
    1, 'Sie tragen das Gebäude - fällt eines, ist es eine andere Verfassung.', 0.0),

  mc('q-o-gg-1', 'o-gesetzgebung',
    'Ab wann ist ein Bundesgesetz wirksam?',
    ['mit dem Beschluss des Nationalrates', 'mit der Beurkundung durch den Bundespräsidenten',
     'mit der Kundmachung im Bundesgesetzblatt', 'mit der Zustimmung des Bundesrates'],
    2, 'Die Kundmachung ist Wirksamkeitsvoraussetzung, nicht bloße Formalität.', 0.2, true),
  mc('q-o-gg-2', 'o-gesetzgebung',
    'Der Bundesrat erhebt Einspruch gegen einen Gesetzesbeschluss. Was kann der Nationalrat tun?',
    ['nichts, das Gesetz ist gescheitert', 'einen Beharrungsbeschluss fassen',
     'den Bundesrat auflösen', 'eine Volksabstimmung anordnen'],
    1, 'Das Einspruchsrecht ist in der Regel nur aufschiebend.', 0.5, true),
  norm('q-o-gg-3', 'o-gesetzgebung',
    'Wie heißt das Publikationsorgan, in dem Bundesgesetze kundgemacht werden? (Ein Wort oder die übliche Abkürzung)',
    ['bundesgesetzblatt', 'bgbl', 'bgbl.', 'bundesgesetzblatt für die republik österreich'],
    'Bundesgesetzblatt, kurz BGBl.', 0.3, true),

  mc('q-o-gr-1', 'o-grundrechte',
    'Der erste Schritt einer Grundrechtsprüfung ist',
    ['die Verhältnismäßigkeit', 'die Bestimmung des Schutzbereichs',
     'die Frage nach dem Gesetzesvorbehalt', 'die Interessenabwägung'],
    1, 'Ohne Schutzbereich gibt es keinen Eingriff und damit nichts zu rechtfertigen.', -0.1, true),
  mc('q-o-gr-2', 'o-grundrechte',
    'Welcher Teilschritt der Verhältnismäßigkeit fragt nach dem gleich wirksamen milderen Mittel?',
    ['Eignung', 'Erforderlichkeit', 'Angemessenheit', 'Legitimität des Ziels'],
    1, 'Erforderlich ist eine Maßnahme nur, wenn kein milderes, gleich wirksames Mittel zur Verfügung steht.', 0.3, true),
  tf('q-o-gr-3', 'o-grundrechte',
    'Die Europäische Menschenrechtskonvention steht in Österreich im Verfassungsrang.',
    0, 'Die Aussage trifft zu. Das ist eine österreichische Besonderheit und deshalb ein beliebtes Prüfungsthema.', 0.4, true),

  mc('q-o-vw-1', 'o-verwaltung',
    'Wodurch unterscheiden sich Verordnung und Bescheid?',
    ['durch die erlassende Behörde', 'durch den Adressatenkreis: generell gegen individuell',
     'durch die Form der Kundmachung allein', 'durch die Bezeichnung im Titel'],
    1, 'Die Verordnung richtet sich an einen unbestimmten Personenkreis, der Bescheid an bestimmte Personen.', 0.1, true),
  mc('q-o-vw-2', 'o-verwaltung',
    'Welcher Bestandteil eines Bescheides wird rechtskräftig?',
    ['die Begründung', 'der Spruch', 'die Rechtsmittelbelehrung', 'die Zustellverfügung'],
    1, 'Nur der Spruch. Die Begründung trägt ihn, erwächst aber nicht selbst in Rechtskraft.', 0.7),

  mc('q-o-rs-1', 'o-rechtsschutz',
    'Welches Gericht kann ein Gesetz wegen Verfassungswidrigkeit aufheben?',
    ['der Oberste Gerichtshof', 'der Verwaltungsgerichtshof',
     'der Verfassungsgerichtshof', 'jedes Landesverwaltungsgericht'],
    2, 'Nur der Verfassungsgerichtshof - man beschreibt ihn deshalb als negativen Gesetzgeber.', -0.4, true),
  mc('q-o-rs-2', 'o-rechtsschutz',
    'Gegen einen Bescheid einer Bezirksverwaltungsbehörde geht es zunächst an',
    ['den Verwaltungsgerichtshof', 'das zuständige Verwaltungsgericht',
     'den Verfassungsgerichtshof', 'den Obersten Gerichtshof'],
    1, 'Erst nach der Entscheidung des Verwaltungsgerichts kommen Revision oder Beschwerde in Betracht.', 0.5),

  // ---------------- Strafrecht ----------------
  mc('q-s-au-1', 's-aufbau',
    'Wie lautet die Reihenfolge der Strafbarkeitsprüfung?',
    ['Schuld, Tatbestand, Rechtswidrigkeit', 'Tatbestand, Rechtswidrigkeit, Schuld',
     'Rechtswidrigkeit, Tatbestand, Schuld', 'Tatbestand, Schuld, Rechtswidrigkeit'],
    1, 'Jede Stufe setzt die vorhergehende voraus.', -0.7, true),
  tf('q-s-au-2', 's-aufbau',
    'Innerhalb des Tatbestands wird zuerst der subjektive, dann der objektive Teil geprüft.',
    1, 'Die Aussage trifft nicht zu. Erst objektiv (Handlung, Erfolg, Kausalität, Zurechnung), dann subjektiv.', -0.2, true),
  mc('q-s-au-3', 's-aufbau',
    'Der Täter irrt über ein objektives Tatbildmerkmal. Rechtsfolge?',
    ['Die Schuld entfällt', 'Der Vorsatz entfällt (Tatbildirrtum)',
     'Die Rechtswidrigkeit entfällt', 'Es ändert nichts'],
    1, 'Der Vorsatz muss alle objektiven Merkmale umfassen; fehlt das Wissen, entfällt er.', 0.8),

  mc('q-s-tb-1', 's-tatbestand',
    'Die Bedingungsformel (conditio sine qua non) führt zu weit. Wodurch wird sie eingegrenzt?',
    ['durch das Analogieverbot', 'durch die objektive Zurechnung',
     'durch die Schuldfähigkeit', 'durch die Verjährung'],
    1, 'Zugerechnet wird nur, wer eine rechtlich missbilligte Gefahr geschaffen hat, die sich im Erfolg verwirklicht.', 0.6, true),
  mc('q-s-tb-2', 's-tatbestand',
    'Welche zusätzliche Voraussetzung verlangt das unechte Unterlassungsdelikt?',
    ['einen schriftlichen Vertrag', 'eine Garantenstellung',
     'ein Geständnis', 'die Strafmündigkeit des Opfers'],
    1, 'Ohne besondere Rechtspflicht zur Erfolgsabwendung ist Untätigbleiben nicht wie ein Tun zu behandeln.', 0.4, true),

  mc('q-s-rw-1', 's-rechtswidrigkeit',
    'Welche Voraussetzung gehört NICHT zur Notwehr?',
    ['gegenwärtiger rechtswidriger Angriff', 'notwendige Verteidigung',
     'Verteidigungswille', 'vorherige Anzeige bei der Polizei'],
    3, 'Notwehr setzt keine behördliche Befassung voraus - das wäre mit der Gegenwärtigkeit des Angriffs unvereinbar.', -0.5, true),
  tf('q-s-rw-2', 's-rechtswidrigkeit',
    'Notwehr ist auch gegen einen rechtmäßigen Angriff möglich.',
    1, 'Die Aussage trifft nicht zu. Die Notwehrlage verlangt einen rechtswidrigen Angriff; fehlt er, endet die Prüfung.', 0.1, true),
  mc('q-s-rw-3', 's-rechtswidrigkeit',
    'Worin unterscheidet sich der rechtfertigende Notstand von der Notwehr?',
    ['Er ist nur bei Sachschäden möglich', 'Er richtet sich gegen einen Unbeteiligten und verlangt eine Interessenabwägung',
     'Er setzt Vorsatz voraus', 'Er gilt nur für Amtsträger'],
    1, 'Weil ein Unbeteiligter getroffen wird, muss das gerettete Interesse deutlich überwiegen.', 0.7),

  mc('q-s-sch-1', 's-schuld',
    'Welches Element gehört zur Schuld?',
    ['die Kausalität', 'das Unrechtsbewusstsein', 'der Erfolgseintritt', 'die Notwehrlage'],
    1, 'Zurechnungsfähigkeit, Unrechtsbewusstsein und Zumutbarkeit rechtmäßigen Verhaltens.', 0.0, true),
  mc('q-s-sch-2', 's-schuld',
    'Der Täter hält den Erfolg ernstlich für möglich und findet sich damit ab. Das ist',
    ['bewusste Fahrlässigkeit', 'bedingter Vorsatz', 'Absicht', 'unbewusste Fahrlässigkeit'],
    1, 'Sich-Abfinden ist das Willenselement des bedingten Vorsatzes. Wer darauf vertraut, dass nichts passiert, handelt bewusst fahrlässig.', 0.9, true),
  tf('q-s-sch-3', 's-schuld',
    'Der strafrechtliche Fahrlässigkeitsmaßstab berücksichtigt auch die persönliche Befähigung des Täters.',
    0, 'Die Aussage trifft zu. Anders als im Zivilrecht wird auf die geistigen und körperlichen Verhältnisse abgestellt.', 0.8),

  mc('q-s-vs-1', 's-versuch',
    'Wann beginnt der strafbare Versuch?',
    ['mit dem Tatentschluss', 'mit der Beschaffung des Tatwerkzeugs',
     'mit der der Ausführung unmittelbar vorangehenden Handlung', 'mit dem Erfolgseintritt'],
    2, 'Bloße Vorbereitungshandlungen sind grundsätzlich straflos.', 0.3, true),
  tf('q-s-vs-2', 's-versuch',
    'Österreich unterscheidet strafrechtlich zwischen Täterschaft und Teilnahme wie das deutsche Recht.',
    1, 'Die Aussage trifft nicht zu. Österreich folgt dem Einheitstäterbegriff: ausführen, bestimmen und beitragen begründen jeweils Täterschaft.', 0.6, true),
  mc('q-s-vs-3', 's-versuch',
    'Der Täter lässt von der Tat ab, weil er ein Polizeifahrzeug bemerkt. Liegt ein strafbefreiender Rücktritt vor?',
    ['Ja, er hat aufgehört', 'Nein, es fehlt die Freiwilligkeit',
     'Ja, wenn kein Schaden entstanden ist', 'Nur bei Vermögensdelikten'],
    1, 'Freiwillig ist der Rücktritt nur, wenn er nicht durch äußeren Zwang veranlasst ist.', 0.4),

  // ---------------- Grundlagen ----------------
  mc('q-g-rb-1', 'g-rechtsbegriff',
    'Der Rechtspositivismus behauptet im Kern, dass',
    ['nur gerechte Normen gelten', 'die Geltung einer Norm von ihrer ordnungsgemäßen Erzeugung abhängt',
     'Recht und Moral identisch sind', 'Gewohnheitsrecht keine Rechtsquelle ist'],
    1, 'Geltung und Inhalt werden getrennt. Die Gegenposition halten naturrechtliche Ansätze.', 0.2, true),
  tf('q-g-rb-2', 'g-rechtsbegriff',
    'Zwang ist nach herrschender Auffassung das Wesen des Rechts, nicht bloß seine Absicherung.',
    1, 'Die Aussage trifft nicht zu. Der organisierte Zwang sichert die Rechtsordnung ab, macht aber nicht ihr Wesen aus.', 0.9),

  mc('q-g-roe-1', 'g-roemisch',
    'Welche Sammlung ließ Kaiser Justinian im 6. Jahrhundert schaffen?',
    ['den Codex Hammurapi', 'das Corpus Iuris Civilis',
     'den Sachsenspiegel', 'die Constitutio Criminalis Carolina'],
    1, 'Kernstücke sind Digesten, Codex und Institutionen.', -0.3, true),
  mc('q-g-roe-2', 'g-roemisch',
    'Wer bearbeitete das wiederentdeckte römische Recht ab dem 11. Jahrhundert durch Randbemerkungen?',
    ['die Kommentatoren', 'die Glossatoren', 'die Pandektisten', 'die Kanonisten'],
    1, 'Die Glossatoren erschlossen den Text; die Kommentatoren machten ihn praxistauglich.', 0.5),
  tf('q-g-roe-3', 'g-roemisch',
    'Rezeption bedeutet, dass das römische Recht als Gesetz in Kraft gesetzt wurde.',
    1, 'Die Aussage trifft nicht zu. Übernommen wurde die wissenschaftliche Bearbeitung und ihre Begrifflichkeit, nicht ein Gesetzesbefehl.', 0.8),

  mc('q-g-abgb-1', 'g-abgb',
    'Wann trat das ABGB in Kraft?',
    ['1776', '1812', '1867', '1920'],
    1, 'Es ist damit eines der ältesten noch geltenden Zivilgesetzbücher Europas.', -0.6, true),
  tf('q-g-abgb-2', 'g-abgb',
    'Das ABGB gilt seit 1812 im Wesentlichen unverändert.',
    1, 'Die Aussage trifft nicht zu. Die Teilnovellen 1914 bis 1916 und zahlreiche spätere Reformen haben es tiefgreifend umgebaut.', 0.3, true),
  mc('q-g-abgb-3', 'g-abgb',
    'Welches Merkmal erklärt die Langlebigkeit des ABGB am besten?',
    ['seine außerordentliche Detailliertheit', 'sein hoher Anteil an offenen Generalklauseln',
     'sein Verfassungsrang', 'seine Unabänderlichkeit'],
    1, 'Offene Formulierungen ließen sich durch Rechtsprechung fortentwickeln, ohne den Text ständig zu ändern.', 0.6)
];
